# Generated by Django 6.0.1 on 2026-01-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Account'), ('CREDIT_CARD', 'Credit Card'), ('LOAN', 'Loan Account'), ('INVESTMENT', 'Investment Account'), ('SYSTEM_EXPENSE', 'System Expense'), ('SYSTEM_INCOME', 'System Income')], max_length=20),
        ),
    ]
