# Generated by Django 6.0.1 on 2026-01-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Account'), ('CREDIT_CARD', 'Credit Card'), ('LOAN', 'Loan Account'), ('INVESTMENT', 'Investment Account'), ('SYSTEM_EXPENSE', 'System Expense'), ('SYSTEM_INCOME', 'System Income'), ('PERSONAL_LEDGER', 'Personal Ledger')], max_length=20),
        ),
    ]
