# Generated by Django 6.0.1 on 2026-01-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseitem',
            name='tags',
        ),
        migrations.AddField(
            model_name='expenseitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='expense_items', to='transactions.tag'),
        ),
    ]
